services:
  client:
    image: gauravd7/rozgaarsathi-client:latest
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

  server:
    image: gauravd7/rozgaarsathi-server:latest
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    environment:
      # Overriding variables from .env to work inside Docker network
      - CLIENT_URL=http://localhost
    networks:
      - app-network

networks:
  app-network:
