version: "3.8"

services:
  backend:
    image: gauravd7/rozgaarsathi-backend:latest
    container_name: rozgaarsathi-backend
    restart: always
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3000:3000"
    networks:
      - rozgaarsathi-network

  frontend:
    image: gauravd7/rozgaarsathi-frontend:latest
    container_name: rozgaarsathi-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - rozgaarsathi-network

  nginx:
    image: nginx:latest
    container_name: rozgaarsathi-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - rozgaarsathi-network

networks:
  rozgaarsathi-network:
    driver: bridge